# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5fae39ffb9fc1dc232665e2b485d9066df4926b645f51b79251113e77b7622c638a044e5a8f7f030b8a2ebde50d8536d709141b05a9f82d760deb21c623a6265

test:
  secret_key_base: c109319851ba67ee6030a6adaa007797f7e1aab4a71934cd2594ae8b8fb76e5072870c595b01d3a1f12594b7adc6bc23c409f7cd0730c6e49435eabe21274fc7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
